// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/user/business/contract/repository.go
//
// Generated by this command:
//
//	mockgen -source=pkg/user/business/contract/repository.go -destination=mocks/pkg/user/business/contract/repository.go -package=contract Repository
//

// Package contract is a generated GoMock package.
package contract

import (
	context "context"
	reflect "reflect"

	repository "github.com/abialemuel/billing-engine/pkg/user/modules/repository"
	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreatePayment mocks base method.
func (m *MockRepository) CreatePayment(ctx context.Context, tx *gorm.DB, payment *repository.Payment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePayment", ctx, tx, payment)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePayment indicates an expected call of CreatePayment.
func (mr *MockRepositoryMockRecorder) CreatePayment(ctx, tx, payment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePayment", reflect.TypeOf((*MockRepository)(nil).CreatePayment), ctx, tx, payment)
}

// CreateSchedule mocks base method.
func (m *MockRepository) CreateSchedule(ctx context.Context, tx *gorm.DB, schedule *repository.LoanSchedule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSchedule", ctx, tx, schedule)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSchedule indicates an expected call of CreateSchedule.
func (mr *MockRepositoryMockRecorder) CreateSchedule(ctx, tx, schedule any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSchedule", reflect.TypeOf((*MockRepository)(nil).CreateSchedule), ctx, tx, schedule)
}

// GetLoanByUserID mocks base method.
func (m *MockRepository) GetLoanByUserID(ctx context.Context, tx *gorm.DB, userID uint) (*repository.Loan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLoanByUserID", ctx, tx, userID)
	ret0, _ := ret[0].(*repository.Loan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLoanByUserID indicates an expected call of GetLoanByUserID.
func (mr *MockRepositoryMockRecorder) GetLoanByUserID(ctx, tx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLoanByUserID", reflect.TypeOf((*MockRepository)(nil).GetLoanByUserID), ctx, tx, userID)
}

// GetOverdueScheduleByLoanID mocks base method.
func (m *MockRepository) GetOverdueScheduleByLoanID(ctx context.Context, tx *gorm.DB, loanID uint) ([]repository.LoanSchedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOverdueScheduleByLoanID", ctx, tx, loanID)
	ret0, _ := ret[0].([]repository.LoanSchedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOverdueScheduleByLoanID indicates an expected call of GetOverdueScheduleByLoanID.
func (mr *MockRepositoryMockRecorder) GetOverdueScheduleByLoanID(ctx, tx, loanID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOverdueScheduleByLoanID", reflect.TypeOf((*MockRepository)(nil).GetOverdueScheduleByLoanID), ctx, tx, loanID)
}

// GetUserByUsername mocks base method.
func (m *MockRepository) GetUserByUsername(ctx context.Context, tx *gorm.DB, username string) (*repository.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByUsername", ctx, tx, username)
	ret0, _ := ret[0].(*repository.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByUsername indicates an expected call of GetUserByUsername.
func (mr *MockRepositoryMockRecorder) GetUserByUsername(ctx, tx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByUsername", reflect.TypeOf((*MockRepository)(nil).GetUserByUsername), ctx, tx, username)
}

// UpdateLoan mocks base method.
func (m *MockRepository) UpdateLoan(ctx context.Context, tx *gorm.DB, loan *repository.Loan) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLoan", ctx, tx, loan)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLoan indicates an expected call of UpdateLoan.
func (mr *MockRepositoryMockRecorder) UpdateLoan(ctx, tx, loan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLoan", reflect.TypeOf((*MockRepository)(nil).UpdateLoan), ctx, tx, loan)
}

// UpdateSchedule mocks base method.
func (m *MockRepository) UpdateSchedule(ctx context.Context, tx *gorm.DB, schedule *repository.LoanSchedule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSchedule", ctx, tx, schedule)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSchedule indicates an expected call of UpdateSchedule.
func (mr *MockRepositoryMockRecorder) UpdateSchedule(ctx, tx, schedule any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSchedule", reflect.TypeOf((*MockRepository)(nil).UpdateSchedule), ctx, tx, schedule)
}
