
version: '3'
services:
  billing-engine:
    build:
      context: .
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: always
  postgres:
    image: postgres:14.4
    environment:
      POSTGRES_DB: billing_engine
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pa55word
    ports:
      - 5432:5432
  jaeger:
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 16686:16686
      - 14268:14268
      - 4317:4317
  migrate:
    image: postgres:14.4
    depends_on:
      - postgres
    volumes:
      - ./migrations:/migrations  # Mount the migrations folder
    entrypoint: ["/bin/bash", "-c", "PGPASSWORD=pa55word psql -h postgres -U root -d billing_engine -f /migrations/migration.sql"]
    restart: "no"

